### ISSUE TITLE
Configuration file editing and setup.

### ISSUE THREAD

**Issue by anand-010** [allenporter/rtsp-to-webrtc-client#12]
I am new to python projects and I have cloned this repo and installed dependencies globally.
I didn't find any configuration.json file and don't know how to run this in python.
Please help me.
And like the original go implementation of rtsp to webrtc is it only supports h264 ?.

**Comment by allenporter** [comment]
Hi. What's configuration.json? What are you trying to accomplish?

Just to clarify, this is a client library for https://github.com/deepch/RTSPtoWebRTC so that it can be used in home assistant.

**Comment by anand-010** [comment]
Oh my mistake I thought it's RTSPtoWebRTC implementation in python.
Than you for the confirmation.
