### ISSUE TITLE
Offer process drops any currently active stream

### ISSUE THREAD

**Issue by wms** [allenporter/rtsp-to-webrtc-client#67]
I've mostly succeeded in configuring Home Assistant + RTSPtoWeb and am pleased with the results to far, but there's one major issue that is prevening me from being able to use this full time.

Whenever a stream is initialized, as part of the offer process, it looks like we make a call to the RTSPtoWeb API to create or update the stream configuration:

https://github.com/allenporter/rtsp-to-webrtc-client/blob/86db8ef18f1d39d303892d52a90565964a861fa8/rtsp_to_webrtc/web_client.py#L211

It appears that updating a stream config via RTSPtoWeb's API causes any currently active streams to drop. I can raise a linked issue over there, but I'm wondering if a quick win can be made here: since we already have the result from `list_streams`, would it be possible to do a comparison of the desired config vs. the current config, and skip the update altogether if none is necessary? Hopefully, this should prevent streams from dropping unnecessarily.

I'd offer to raise a PR, but I'm not a Python guy.

**Comment by allenporter** [comment]
Makes sense, and does not seem TOO hard.

**Comment by wms** [comment]
I was able to sidestep this issue temporarily by cloning the `rtsp_to_webrtc` Integration and modifying it so that it effectively skips an insert/update operation:

https://github.com/wms/rtsp_to_webrtc_wms/blob/master/__init__.py#L70-L76

This means that:

1. Each stream must be manually configured in RTSPtoWeb
2. Each stream must have a name that matches the Entity ID
3. The RTSP URL in the HA config itself is effectively ignored

However, this is a compromise I can deal with, as my feeds are now running with near-zero latency and can watch the feeds from anywhere without breaking existing connections :)

**Comment by gfduszynski** [comment]
I've applied @wms changes and it works for me as a temporary fix.

**Comment by allenporter** [comment]
Fixed in #78 
Will do some testing then pull into home assistant.

Thanks for the excellent bug report, I really appreciate it.

**Comment by wms** [comment]
> Fixed in #78 Will do some testing then pull into home assistant.
> 
> Thanks for the excellent bug report, I really appreciate it.

Thank _you_ for putting building this integation and addressing the bug in the proper way 👍🏻

**Comment by allenporter** [comment]
👍🏼 this is tagged for 2022.4.2 patch release.

**Comment by wms** [comment]
@allenporter Just wanted to check in and say that I've upgrade to HA 2022.4.5, removed my fork and this is now working like a treat! Great job, man.
